# Generated by Django 3.1.1 on 2020-10-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201014_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_category',
            new_name='Item_categorie',
        ),
    ]
