# Generated by Django 3.1.1 on 2020-10-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201014_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ctg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='categ', to='auctions.categorie'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.URLField(max_length=150),
        ),
    ]
