# Generated by Django 3.1.1 on 2020-10-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201014_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='ctg',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='img_url',
            new_name='image_URL',
        ),
    ]
