# Generated by Django 3.1.1 on 2020-10-15 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201015_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(related_name='productBids', to='auctions.Listing'),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
