# Generated by Django 3.1.1 on 2020-10-16 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ManyToManyField(related_name='itemsForSale', to=settings.AUTH_USER_MODEL),
        ),
    ]
