# Generated by Django 3.1.1 on 2020-10-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20201016_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_URL',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
