# Generated by Django 3.1.1 on 2020-10-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201019_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_item',
            new_name='wishlist_items',
        ),
    ]
