# Generated by Django 3.1.1 on 2020-10-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20201019_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_items',
            new_name='items',
        ),
    ]
