# Generated by Django 3.1.1 on 2020-10-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20201024_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_by', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auctions.listing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
