# Generated by Django 3.1.1 on 2020-10-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_categorie',
        ),
    ]
